# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: associate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssociate.proto\x12\tAssociate\"$\n\x04\x44\x61ta\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x02 \x01(\x07\"\xe4\x02\n\x08ServerRx\x12\x16\n\x0e\x61ssociation_id\x18\x01 \x01(\r\x12\x17\n\x0fsequence_num_bi\x18\x02 \x01(\r\x12\x35\n\tassoc_req\x18\x03 \x01(\x0b\x32 .Associate.ServerRx.AssociateReqH\x00\x12\x44\n\x11\x61ssoc_release_req\x18\x04 \x01(\x0b\x32\'.Associate.ServerRx.AssociateReleaseReqH\x00\x12\x1f\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x0f.Associate.DataH\x00\x12:\n\x0ekeep_alive_req\x18\x06 \x01(\x0b\x32 .Associate.ServerRx.KeepAliveReqH\x00\x1a\x1f\n\x0c\x41ssociateReq\x12\x0f\n\x07version\x18\x01 \x01(\r\x1a\x15\n\x13\x41ssociateReleaseReq\x1a\x0e\n\x0cKeepAliveReqB\x05\n\x03Msg\"\xe7\x03\n\x08ServerTx\x12\x16\n\x0e\x61ssociation_id\x18\x01 \x01(\r\x12\x18\n\x10sequence_num_uni\x18\x02 \x01(\r\x12\x17\n\x0fsequence_num_bi\x18\x03 \x01(\r\x12\x35\n\tassoc_rep\x18\x04 \x01(\x0b\x32 .Associate.ServerTx.AssociateRepH\x00\x12\x44\n\x11\x61ssoc_release_rep\x18\x05 \x01(\x0b\x32\'.Associate.ServerTx.AssociateReleaseRepH\x00\x12\x1f\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x0f.Associate.DataH\x00\x12:\n\x0ekeep_alive_rep\x18\x07 \x01(\x0b\x32 .Associate.ServerTx.KeepAliveRepH\x00\x1a\x87\x01\n\x0c\x41ssociateRep\x12@\n\x0bstatus_code\x18\x01 \x01(\x0e\x32+.Associate.ServerTx.AssociateRep.StatusCode\"5\n\nStatusCode\x12\t\n\x05UNDEF\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bVERSION_ERR\x10\x02\x1a\x15\n\x13\x41ssociateReleaseRep\x1a\x0e\n\x0cKeepAliveRepB\x05\n\x03Msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'associate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATA']._serialized_start=30
  _globals['_DATA']._serialized_end=66
  _globals['_SERVERRX']._serialized_start=69
  _globals['_SERVERRX']._serialized_end=425
  _globals['_SERVERRX_ASSOCIATEREQ']._serialized_start=348
  _globals['_SERVERRX_ASSOCIATEREQ']._serialized_end=379
  _globals['_SERVERRX_ASSOCIATERELEASEREQ']._serialized_start=381
  _globals['_SERVERRX_ASSOCIATERELEASEREQ']._serialized_end=402
  _globals['_SERVERRX_KEEPALIVEREQ']._serialized_start=404
  _globals['_SERVERRX_KEEPALIVEREQ']._serialized_end=418
  _globals['_SERVERTX']._serialized_start=428
  _globals['_SERVERTX']._serialized_end=915
  _globals['_SERVERTX_ASSOCIATEREP']._serialized_start=734
  _globals['_SERVERTX_ASSOCIATEREP']._serialized_end=869
  _globals['_SERVERTX_ASSOCIATEREP_STATUSCODE']._serialized_start=816
  _globals['_SERVERTX_ASSOCIATEREP_STATUSCODE']._serialized_end=869
  _globals['_SERVERTX_ASSOCIATERELEASEREP']._serialized_start=871
  _globals['_SERVERTX_ASSOCIATERELEASEREP']._serialized_end=892
  _globals['_SERVERTX_KEEPALIVEREP']._serialized_start=894
  _globals['_SERVERTX_KEEPALIVEREP']._serialized_end=908
# @@protoc_insertion_point(module_scope)
