# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tblctlsuite.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tblctl_pb2 as tblctl__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tblctlsuite.proto\x12\x0bTblCtlSuite\x1a\x0ctblctl.proto\"9\n\x08ServerRx\x12$\n\x03\x63tl\x18\x01 \x01(\x0b\x32\x15.TblCtlProto.ServerRxH\x00\x42\x07\n\x05Prtcl\"9\n\x08ServerTx\x12$\n\x03\x63tl\x18\x01 \x01(\x0b\x32\x15.TblCtlProto.ServerTxH\x00\x42\x07\n\x05Prtclb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tblctlsuite_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SERVERRX']._serialized_start=48
  _globals['_SERVERRX']._serialized_end=105
  _globals['_SERVERTX']._serialized_start=107
  _globals['_SERVERTX']._serialized_end=164
# @@protoc_insertion_point(module_scope)
